### ISSUE TITLE
Feature Request: Planet Satellites in Dropdown

### ISSUE THREAD

**Issue by braymondplanetfed** [jdp1g09/node-red-satellites#10]
Any chance you could add the Planet Labs satellites in the dropdown to group all of them into one option?

https://www.celestrak.com/NORAD/elements/planet.txt

**Comment by dceejay** [comment]
Not an unreasonable request... now in v0.5.0

**Comment by braymondplanetfed** [comment]
Awesome Sauce! Thanks
